algoritmo "A Catraca do Laboratório"
// Disciplina  : Linguagem e Lógica de Programação
// Professor   : Ricardo
// Autor(a)    : Marco

var

    ano:inteiro

inicio
    escreval("Digite seu ano de nascimento: ")
    leia(ano)
    escreval("Sua idade é: ", 2026 - ano)
    se(2026 - ano) >= 18 entao
        escreval ("Acesso Liberado")
    senao
        escreval("Acesso Negado")
    fimse


fimalgoritmo